name: Build images for gchr.io

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE: "ghcr.io/${{ github.repository_owner }}/activemq"
  LATEST_VERSION: "5.18.2"
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build:
    name: Build
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: "5.18.2"
            latest: "latest"
          - version: "5.18.1"
          - version: "5.18.0"
          # AWS engine versions: https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/activemq-version-management.html
          - version: "5.17.3"
          - version: "5.17.2"
          - version: "5.17.1"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Force build if workflow_dispatch or re-run
        if: github.event_name == 'workflow_dispatch' || github.run_attempt != '1'
        run: echo "FORCE_BUILD=1" >> "$GITHUB_ENV"
      - name: Add "latest" as an additional tag
        if: matrix.latest
        run: echo "ADDITIONAL_TAGS=,$IMAGE:latest" >> "$GITHUB_ENV"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: "${{ env.IMAGE }}:${{ matrix.version }}${{ env.ADDITIONAL_TAGS }}"
